image:
  file: gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-preview
  - port: 6379
    onOpen: ignore
tasks:
  - name: "Start the Redis server"
    command: redis-server
  - name: "Start the Rails server"
    init: bin/setup && bundle exec rake assets:precompile
    command: bin/rails server -b 0.0.0.0

